// <auto-generated />
using System;
using FarmaciaSantaRita.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmaciaSantaRita.Migrations
{
    [DbContext(typeof(FarmaciabdContext))]
    [Migration("20251202174233_InicialLimpia")]
    partial class InicialLimpia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmaciaSantaRita.Models.Boletum", b =>
                {
                    b.Property<int>("Idboleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBoleta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idboleta"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("Idproveedor")
                        .HasColumnType("int")
                        .HasColumnName("IDProveedor");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuario");

                    b.Property<int>("ImporteFinal")
                        .HasColumnType("int");

                    b.Property<string>("Transfer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Idboleta");

                    b.HasIndex("Idproveedor");

                    b.HasIndex("Idusuario");

                    b.ToTable("Boleta");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Cliente", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcliente"));

                    b.Property<string>("DireccionCliente")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("EstadoDePago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Idcliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Compra", b =>
                {
                    b.Property<int>("Idcompras")
                        .HasColumnType("int")
                        .HasColumnName("IDCompras");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateOnly>("FechaCompra")
                        .HasColumnType("date");

                    b.Property<int>("Idcliente")
                        .HasColumnType("int")
                        .HasColumnName("IDCliente");

                    b.Property<int>("IdlineaDeCompra")
                        .HasColumnType("int")
                        .HasColumnName("IDLineaDeCompra");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuario");

                    b.Property<decimal>("MontoCompra")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Idcompras");

                    b.HasIndex("Idcliente");

                    b.HasIndex("IdlineaDeCompra");

                    b.HasIndex("Idusuario");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Inasistencium", b =>
                {
                    b.Property<int>("Idinasistencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDInasistencias");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idinasistencias"));

                    b.Property<DateOnly>("FechaInasistencia")
                        .HasColumnType("date");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int")
                        .HasColumnName("IDUsuario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Idinasistencias");

                    b.HasIndex("Idusuario");

                    b.ToTable("Inasistencia");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.LineaDeCompra", b =>
                {
                    b.Property<int>("IdlineaDeCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLineaDeCompra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdlineaDeCompra"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Idproducto")
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    b.HasKey("IdlineaDeCompra");

                    b.HasIndex("Idproducto");

                    b.ToTable("LineaDeCompra", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Producto", b =>
                {
                    b.Property<int>("Idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproducto"));

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Idproducto");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Proveedor", b =>
                {
                    b.Property<int>("Idproveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDProveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idproveedor"));

                    b.Property<string>("CorreoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TelefonoProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Idproveedor");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Usuario", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idusuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .HasColumnName("DNI")
                        .IsFixedLength();

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Idusuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Boletum", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Proveedor", "IdproveedorNavigation")
                        .WithMany("Boleta")
                        .HasForeignKey("Idproveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Boleta_Proveedor");

                    b.HasOne("FarmaciaSantaRita.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Boleta")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("FK_Boleta_Usuarios");

                    b.Navigation("IdproveedorNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Compra", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Cliente", "IdclienteNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("Idcliente")
                        .IsRequired()
                        .HasConstraintName("FK_Compras_Clientes");

                    b.HasOne("FarmaciaSantaRita.Models.LineaDeCompra", "IdlineaDeCompraNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdlineaDeCompra")
                        .IsRequired()
                        .HasConstraintName("FK_Compras_LineaDeCompra");

                    b.HasOne("FarmaciaSantaRita.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("FK_Compras_Usuarios");

                    b.Navigation("IdclienteNavigation");

                    b.Navigation("IdlineaDeCompraNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Inasistencium", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Inasistencia")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("FK_Inasistencia_Usuarios");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.LineaDeCompra", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Producto", "IdproductoNavigation")
                        .WithMany("LineaDeCompras")
                        .HasForeignKey("Idproducto")
                        .IsRequired()
                        .HasConstraintName("FK_LineaDeCompra_Producto");

                    b.Navigation("IdproductoNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Cliente", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.LineaDeCompra", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Producto", b =>
                {
                    b.Navigation("LineaDeCompras");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Proveedor", b =>
                {
                    b.Navigation("Boleta");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Usuario", b =>
                {
                    b.Navigation("Boleta");

                    b.Navigation("Compras");

                    b.Navigation("Inasistencia");
                });
#pragma warning restore 612, 618
        }
    }
}
