// <auto-generated />
using System;
using FarmaciaSantaRita.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmaciaSantaRita.Migrations
{
    [DbContext(typeof(FarmaciabdContext))]
    partial class FarmaciabdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmaciaSantaRita.Models.Boletum", b =>
                {
                    b.Property<int>("Idboleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDBoleta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idboleta"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Idproveedor")
                        .HasColumnType("integer")
                        .HasColumnName("IDProveedor");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("IDUsuario");

                    b.Property<int>("ImporteFinal")
                        .HasColumnType("integer");

                    b.Property<string>("Transfer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Idboleta");

                    b.HasIndex("Idproveedor");

                    b.HasIndex("Idusuario");

                    b.ToTable("Boleta", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Cliente", b =>
                {
                    b.Property<int>("Idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDCliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcliente"));

                    b.Property<string>("DNI")
                        .HasColumnType("text")
                        .HasColumnName("DNI");

                    b.Property<string>("DireccionCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DireccionCliente");

                    b.Property<string>("EstadoDePago")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EstadoPago");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreCliente");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TelefonoCliente");

                    b.HasKey("Idcliente");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Compra", b =>
                {
                    b.Property<int>("Idcompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDCompras");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcompras"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("EstadoDePago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("FechaCompra")
                        .HasColumnType("date");

                    b.Property<int>("Idcliente")
                        .HasColumnType("integer")
                        .HasColumnName("IDCliente");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("IDUsuario");

                    b.Property<decimal>("MontoCompra")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Idcompras");

                    b.HasIndex("Idcliente");

                    b.HasIndex("Idusuario");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Inasistencium", b =>
                {
                    b.Property<int>("Idinasistencias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDInasistencias");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idinasistencias"));

                    b.Property<DateOnly>("FechaInasistencia")
                        .HasColumnType("date");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("IDUsuario");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Idinasistencias");

                    b.HasIndex("Idusuario");

                    b.ToTable("Inasistencia", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.LineaDeCompra", b =>
                {
                    b.Property<int>("Idlineadecompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDLineaDeCompra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idlineadecompra"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("Idcompras")
                        .HasColumnType("integer")
                        .HasColumnName("IDCompras");

                    b.Property<int>("Idproducto")
                        .HasColumnType("integer")
                        .HasColumnName("IDProducto");

                    b.HasKey("Idlineadecompra");

                    b.HasIndex("Idcompras");

                    b.HasIndex("Idproducto");

                    b.ToTable("LineaDeCompra", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Producto", b =>
                {
                    b.Property<int>("Idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDProducto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idproducto"));

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NombreProducto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("PrecioUnitario");

                    b.HasKey("Idproducto");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Proveedor", b =>
                {
                    b.Property<int>("Idproveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDProveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idproveedor"));

                    b.Property<string>("CorreoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoProveedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TelefonoProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Idproveedor");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Usuario", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDUsuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idusuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character(8)")
                        .HasColumnName("DNI")
                        .IsFixedLength();

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Idusuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Vacacion", b =>
                {
                    b.Property<int>("IdVacaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDVacaciones");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVacaciones"));

                    b.Property<int>("DiasFavor")
                        .HasColumnType("integer")
                        .HasColumnName("DiasFavor");

                    b.Property<int>("DiasVacaciones")
                        .HasColumnType("integer")
                        .HasColumnName("DiasVacaciones");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaInicio");

                    b.Property<int>("Idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("IDUsuario");

                    b.Property<string>("NombreEmpleadoRegistrado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("NombreEmpleadoRegistrado");

                    b.HasKey("IdVacaciones")
                        .HasName("PK_Vacaciones");

                    b.HasIndex("Idusuario");

                    b.ToTable("Vacaciones", (string)null);
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Boletum", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Proveedor", "IdproveedorNavigation")
                        .WithMany("Boleta")
                        .HasForeignKey("Idproveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Boleta_Proveedor");

                    b.HasOne("FarmaciaSantaRita.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Boleta")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("FK_Boleta_Usuarios");

                    b.Navigation("IdproveedorNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Compra", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Cliente", "IdclienteNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("Idcliente")
                        .IsRequired()
                        .HasConstraintName("FK_Compras_Clientes");

                    b.HasOne("FarmaciaSantaRita.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("FK_Compras_Usuarios");

                    b.Navigation("IdclienteNavigation");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Inasistencium", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Inasistencia")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("FK_Inasistencia_Usuarios");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.LineaDeCompra", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Compra", "IdcomprasNavigation")
                        .WithMany("LineaDeCompras")
                        .HasForeignKey("Idcompras")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LineaDeCompra_Compras");

                    b.HasOne("FarmaciaSantaRita.Models.Producto", "IdproductoNavigation")
                        .WithMany("LineaDeCompras")
                        .HasForeignKey("Idproducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdcomprasNavigation");

                    b.Navigation("IdproductoNavigation");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Vacacion", b =>
                {
                    b.HasOne("FarmaciaSantaRita.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Idusuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vacaciones_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Cliente", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Compra", b =>
                {
                    b.Navigation("LineaDeCompras");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Producto", b =>
                {
                    b.Navigation("LineaDeCompras");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Proveedor", b =>
                {
                    b.Navigation("Boleta");
                });

            modelBuilder.Entity("FarmaciaSantaRita.Models.Usuario", b =>
                {
                    b.Navigation("Boleta");

                    b.Navigation("Compras");

                    b.Navigation("Inasistencia");
                });
#pragma warning restore 612, 618
        }
    }
}
